### ISSUE TITLE
TLS-Attacker 2.5 breaks TLS-Scanner

### ISSUE THREAD

**Issue by m-terlinde** [RUB-NDS/TLS-Scanner#30]
Renameing class "NamedCurve" to "NamedGroup" breaks TLS-Scanner on various points.

Also there are some changes in the tlsConfig that breaks some probes (i. e. ExtensionProbe).

**Comment by ic0ns** [comment]
There are already some branches in TLS-Scanner which work with TLS-Attacker 2.5 but for now the master branch only supports TLS-Attacker 2.4

**Comment by m-terlinde** [comment]
Ah great, I'll use the 2.5 branch.
Thanks for that!
