### ISSUE TITLE
Maven build fails

### ISSUE THREAD

**Issue by fhred** [RUB-NDS/TLS-Scanner#62]
I've no experience with maven so I'm a bit at loss here:

- I've cloned the TLS-Attacker and Scanner Repos and build the TLS-Attacker (downgraded my Java to version 8 for that), that worked flawlessly.
- Executing `mvn clean package` in the TLS-Scanner Repo I get the error 
  `
  [ERROR] Failed to execute goal on project TLS-Scanner: Could not resolve dependencies for project de.rub.nds.tlsscanner:TLS-Scanner:jar:3.0.2: The following artifacts could not be resolved: de.rub.nds.tlsattacker:TLS-Core:jar:3.3.1, de.rub.nds.tlsattacker:Attacks:jar:3.3.1: Could not find artifact de.rub.nds.tlsattacker:TLS-Core:jar:3.3.1 in central (https://repo.maven.apache.org/maven2)
  `

I suppose that it is a problem on your side, if that's not the case: any idea what the problem might be?

**Comment by Immortalem** [comment]
I'm not entirely sure but currently the master branch of TLS-Attacker is 3.4.0 while TLS-Scanner requires 3.3.1. I don't know if there are any incompatibilities but a quick workaround for you should be to clone TLS-Attacker 3.3.1 and build that.

**Comment by fhred** [comment]
That worked, thanks!

**Comment by bennysp** [comment]
This is happening when you use the TLS-Scanner Dockerfile and issue the build command.

**docker build . -t tlsscanner**
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.679 s
[INFO] Finished at: 2020-07-17T16:33:35Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project TLS-Scanner: Could not resolve dependencies for project de.rub.nds.tlsscanner:TLS-Scanner:jar:3.0.2: The following artifacts could not be resolved: de.rub.nds.tlsattacker:TLS-Core:jar:3.3.1, de.rub.nds.tlsattacker:Attacks:jar:3.3.1: Could not find artifact de.rub.nds.tlsattacker:TLS-Core:jar:3.3.1 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
The command '/bin/sh -c mvn clean install -DskipTests=true' returned a non-zero code: 1
```

**Comment by Immortalem** [comment]
Yes the Dockerfile will be updated in the future to avoid this problem. For now you can add `--branch 3.3.1` to the git clone command for the TLS-Attacker.
