### ISSUE TITLE
Fail to compile and using docker

### ISSUE THREAD

**Issue by 0xVIC** [RUB-NDS/TLS-Scanner#66]
mvn clean package

`[INFO] BUILD FAILURE
[ERROR] Failed to execute goal on project TLS-Scanner: Could not resolve dependencies for project de.rub.nds.tlsscanner:TLS-Scanner:jar:3.0.2: The following artifacts could not be resolved: de.rub.nds.tlsattacker:TLS-Core:jar:3.3.1, de.rub.nds.tlsattacker:Attacks:jar:3.3.1: Failure to find de.rub.nds.tlsattacker:TLS-Core:jar:3.3.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project TLS-Scanner: Could not resolve dependencies for project de.rub.nds.tlsscanner:TLS-Scanner:jar:3.0.2: The following artifacts could not be resolved: de.rub.nds.tlsattacker:TLS-Core:jar:3.3.1, de.rub.nds.tlsattacker:Attacks:jar:3.3.1: Failure to find de.rub.nds.tlsattacker:TLS-Core:jar:3.3.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced`

Machine:
Apache Maven 3.6.3
Linux PC 5.6.0-kali2-amd64 #1 SMP Debian 5.6.14-2kali1 (2020-06-10) x86_64 GNU/Linux

Docker error:
`[ERROR] Failed to execute goal on project Utils: Could not resolve dependencies for project de.rub.nds.tlsattacker:Utils:jar:3.5.0: Could not find artifact de.rub.nds:X509Attacker:jar:1.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]`

**Comment by ic0ns** [comment]
We are working on a new version which fixes this. In the meantime see: #64

**Comment by ic0ns** [comment]
should be fixed in version 4.0.0.
